# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tom De Smedt
tagline:          ''
description:      'A Blog on my research in Environmental Epidemiology. Focussing on R programming, ecologic studies, spatial analysis and data visualisation. Side projects included. Hosted by GitHub'
url:              https://tdesmedt.github.io/
baseurl:          '/'
paginate:         5

author:
  name:           'Tom De Smedt'
  url:            https://tdesmedt.github.io/

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/tdesmedt/tdesmedt.github.com
